//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba16
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рег результ.
    /// </summary>
    // *** Start programmer edit section *** (РегРезульт CustomAttributes)

    // *** End programmer edit section *** (РегРезульт CustomAttributes)
    [AutoAltered()]
    [Caption("Рег результ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегРезультE", new string[] {
            "ДатРегРезСобес as \'Дат рег рез собес\'",
            "ПринятНаРаб as \'Принят на раб\'",
            "НеПринНаРаб as \'Не прин на раб\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "ПланирСобес as \'Планир собес\'",
            "ПланирСобес.ИметьПриСебе as \'Иметь при себе\'"}, Hidden=new string[] {
            "Организация.Наименование",
            "ПланирСобес.ИметьПриСебе"})]
    [AssociatedDetailViewAttribute("РегРезультE", "ТЧРегРезульт", "ТЧРегРезультE", true, "", "Т ч рег результ", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("РегРезультE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("РегРезультE", "ПланирСобес", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ИметьПриСебе")]
    [View("РегРезультL", new string[] {
            "ДатРегРезСобес as \'Дат рег рез собес\'",
            "ПринятНаРаб as \'Принят на раб\'",
            "НеПринНаРаб as \'Не прин на раб\'",
            "Организация.Наименование as \'Наименование\'",
            "ПланирСобес.ИметьПриСебе as \'Иметь при себе\'"})]
    public class РегРезульт : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатРегРезСобес;
        
        private bool fПринятНаРаб;
        
        private bool fНеПринНаРаб;
        
        private IIS.Proba16.Организация fОрганизация;
        
        private IIS.Proba16.ПланирСобес fПланирСобес;
        
        private IIS.Proba16.DetailArrayOfТЧРегРезульт fТЧРегРезульт;
        
        // *** Start programmer edit section *** (РегРезульт CustomMembers)

        // *** End programmer edit section *** (РегРезульт CustomMembers)

        
        /// <summary>
        /// ДатРегРезСобес.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес CustomAttributes)
        public virtual System.DateTime ДатРегРезСобес
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Get start)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Get start)
                System.DateTime result = this.fДатРегРезСобес;
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Get end)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Set start)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Set start)
                this.fДатРегРезСобес = value;
                // *** Start programmer edit section *** (РегРезульт.ДатРегРезСобес Set end)

                // *** End programmer edit section *** (РегРезульт.ДатРегРезСобес Set end)
            }
        }
        
        /// <summary>
        /// НеПринНаРаб.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.НеПринНаРаб CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.НеПринНаРаб CustomAttributes)
        public virtual bool НеПринНаРаб
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.НеПринНаРаб Get start)

                // *** End programmer edit section *** (РегРезульт.НеПринНаРаб Get start)
                bool result = this.fНеПринНаРаб;
                // *** Start programmer edit section *** (РегРезульт.НеПринНаРаб Get end)

                // *** End programmer edit section *** (РегРезульт.НеПринНаРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.НеПринНаРаб Set start)

                // *** End programmer edit section *** (РегРезульт.НеПринНаРаб Set start)
                this.fНеПринНаРаб = value;
                // *** Start programmer edit section *** (РегРезульт.НеПринНаРаб Set end)

                // *** End programmer edit section *** (РегРезульт.НеПринНаРаб Set end)
            }
        }
        
        /// <summary>
        /// ПринятНаРаб.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ПринятНаРаб CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ПринятНаРаб CustomAttributes)
        public virtual bool ПринятНаРаб
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ПринятНаРаб Get start)

                // *** End programmer edit section *** (РегРезульт.ПринятНаРаб Get start)
                bool result = this.fПринятНаРаб;
                // *** Start programmer edit section *** (РегРезульт.ПринятНаРаб Get end)

                // *** End programmer edit section *** (РегРезульт.ПринятНаРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ПринятНаРаб Set start)

                // *** End programmer edit section *** (РегРезульт.ПринятНаРаб Set start)
                this.fПринятНаРаб = value;
                // *** Start programmer edit section *** (РегРезульт.ПринятНаРаб Set end)

                // *** End programmer edit section *** (РегРезульт.ПринятНаРаб Set end)
            }
        }
        
        /// <summary>
        /// Рег результ.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.Организация CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Proba16.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.Организация Get start)

                // *** End programmer edit section *** (РегРезульт.Организация Get start)
                IIS.Proba16.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (РегРезульт.Организация Get end)

                // *** End programmer edit section *** (РегРезульт.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.Организация Set start)

                // *** End programmer edit section *** (РегРезульт.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (РегРезульт.Организация Set end)

                // *** End programmer edit section *** (РегРезульт.Организация Set end)
            }
        }
        
        /// <summary>
        /// Рег результ.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ПланирСобес CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ПланирСобес CustomAttributes)
        [PropertyStorage(new string[] {
                "ПланирСобес"})]
        [NotNull()]
        public virtual IIS.Proba16.ПланирСобес ПланирСобес
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Get start)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Get start)
                IIS.Proba16.ПланирСобес result = this.fПланирСобес;
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Get end)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Set start)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Set start)
                this.fПланирСобес = value;
                // *** Start programmer edit section *** (РегРезульт.ПланирСобес Set end)

                // *** End programmer edit section *** (РегРезульт.ПланирСобес Set end)
            }
        }
        
        /// <summary>
        /// Рег результ.
        /// </summary>
        // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт CustomAttributes)

        // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт CustomAttributes)
        public virtual IIS.Proba16.DetailArrayOfТЧРегРезульт ТЧРегРезульт
        {
            get
            {
                // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт Get start)

                // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт Get start)
                if ((this.fТЧРегРезульт == null))
                {
                    this.fТЧРегРезульт = new IIS.Proba16.DetailArrayOfТЧРегРезульт(this);
                }
                IIS.Proba16.DetailArrayOfТЧРегРезульт result = this.fТЧРегРезульт;
                // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт Get end)

                // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт Set start)

                // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт Set start)
                this.fТЧРегРезульт = value;
                // *** Start programmer edit section *** (РегРезульт.ТЧРегРезульт Set end)

                // *** End programmer edit section *** (РегРезульт.ТЧРегРезульт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегРезультE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегРезультE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегРезультE", typeof(IIS.Proba16.РегРезульт));
                }
            }
            
            /// <summary>
            /// "РегРезультL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегРезультL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегРезультL", typeof(IIS.Proba16.РегРезульт));
                }
            }
        }
    }
}
